# File version
version: "3.7"


services:

  # Item-app container configuration
  item-app:

    # Currently app using following version (v1)
    image: item-app:v1
  
    # Reversing port from 80 to 8080, change the host port if is already used by another service
    ports:
      - 80:8080

    # This environment variables are needed by the app to connect to DB Host
    environment:
      - NODE_ENV=production
      - DB_HOST=item-db
    
    # App will start once DB Host is running
    depends_on:
      - item-db

    # Current app working directory
    working_dir: /app

    # Folder where app is stored
    volumes:
      - ./:/app

    # start the app once mongodb is ready
    command: sh -c "node ./bin/www"

    # self restarting when error occurs
    restart: on-failure


  # Mongodb container configuration 
  item-db:

    # Current mongodb image
    image: mongo:3

    # Using default port
    ports:
      - 27017:27017

    # Folder where db data is stored
    volumes:
      - app-db:/data/db


# common share volume between app and database
volumes:

  app-db: