# File version
version: "3.7"


services:

  # Item-app container configuration
  item-app:

    # Currently app using following version (v1)
    image: teddybman/item-app:v1
  
    # Reversing port from 80 to 8080, change the host port if is already used by another service
    ports:
      - 80:8080
  
    # App will start once DB Host is running
    depends_on:
      - item-db

    # Folder where app is stored
    volumes:
      - ./:/app

    # self restarting when error occurs
    restart: on-failure


  # Mongodb container configuration 
  item-db:

    # Current mongodb image
    image: mongo:3

    # Using default port
    ports:
      - 27017:27017

    # Folder where db data is stored
    volumes:
      - app-db:/data/db


# common share volume between app and database
volumes:

  app-db: